#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         5
bspc config window_gap          12

bspc config top_padding		0
bspc config left_padding	0
bspc config right_padding	0
bspc config bottom_padding	0

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true

feh --bg-scale ~/wp.jpg &
redshift -l 59.91273:10.74609 &
polybar topbar &
